In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from pylab import rcParams
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report


np.set_printoptions(precision=4, suppress=True)
%matplotlib inline
rcParams['figure.figsize'] = 7,4
sns.set_style('whitegrid')

caminho = '/home/leonardo/Artificial Intelligence/LinkedIn Learning/arquivos_de_exercicios_python_para_ciencia_dados_basico/dados/mtcars.csv'
carros = pd.read_csv(caminho)
carros.columns = ['nomes', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'qnt_marchas', 'carb']

X = carros[['mpg', 'disp', 'hp', 'wt']].values

y = carros['am'].values

[[ 21.    160.    110.      2.62 ]
 [ 21.    160.    110.      2.875]
 [ 22.8   108.     93.      2.32 ]
 [ 21.4   258.    110.      3.215]
 [ 18.7   360.    175.      3.44 ]
 [ 18.1   225.    105.      3.46 ]
 [ 14.3   360.    245.      3.57 ]
 [ 24.4   146.7    62.      3.19 ]
 [ 22.8   140.8    95.      3.15 ]
 [ 19.2   167.6   123.      3.44 ]
 [ 17.8   167.6   123.      3.44 ]
 [ 16.4   275.8   180.      4.07 ]
 [ 17.3   275.8   180.      3.73 ]
 [ 15.2   275.8   180.      3.78 ]
 [ 10.4   472.    205.      5.25 ]
 [ 10.4   460.    215.      5.424]
 [ 14.7   440.    230.      5.345]
 [ 32.4    78.7    66.      2.2  ]
 [ 30.4    75.7    52.      1.615]
 [ 33.9    71.1    65.      1.835]
 [ 21.5   120.1    97.      2.465]
 [ 15.5   318.    150.      3.52 ]
 [ 15.2   304.    150.      3.435]
 [ 13.3   350.    245.      3.84 ]
 [ 19.2   400.    175.      3.845]
 [ 27.3    79.     66.      1.935]
 [ 26.    120.3    91.      2.14 ]
 [ 30.4    95.1   113.      1.513]
 [ 15.8   351.    26

In [6]:
X = preprocessing.scale(X)

In [7]:
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=.33, random_state=17)

In [8]:
clf = KNeighborsClassifier()
clf.fit(X_treino, y_treino)

print(clf)

KNeighborsClassifier()


In [9]:
y_esperado = y_teste
y_predito = clf.predict(X_teste)

print(classification_report(y_esperado, y_predito))

              precision    recall  f1-score   support

           0       0.71      1.00      0.83         5
           1       1.00      0.67      0.80         6

    accuracy                           0.82        11
   macro avg       0.86      0.83      0.82        11
weighted avg       0.87      0.82      0.82        11

