In [2]:
import numpy as np
from numpy.random import randn

In [3]:
np.set_printoptions(precision=2)

In [4]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [5]:
np.random.seed(25)
b = randn(6)
b

array([ 0.23,  1.03, -0.84, -0.59, -0.96, -0.22])

In [6]:
c = np.arange(1, 35)
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [7]:
a + b

array([1.23, 3.03, 2.16, 3.41, 4.04, 5.78])

In [8]:
a * 10

array([10, 20, 30, 40, 50, 60])

In [9]:
a / b

array([  4.38,   1.95,  -3.57,  -6.77,  -5.23, -26.99])

In [10]:
a - b

array([0.77, 0.97, 3.84, 4.59, 5.96, 6.22])

In [11]:
matriz_a = np.array([[2,4,6], [5,2,7], [3,9,4]])
matriz_b = np.array([[1,3,5], [2,7,4], [5,6,2]])

np.dot(matriz_a, matriz_b)


array([[40, 70, 38],
       [44, 71, 47],
       [41, 96, 59]])